/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HealthHive;

import org.junit.jupiter.api.Test;

import Server.HealthHive;


class AppTest {
    @Test void appHasAGreeting() {
        HealthHive classUnderTest = new HealthHive();
        classUnderTest.donothing();
    }
}
